In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df_2015 = pd.read_csv('BioProfile_Destructive_Facts_2015.csv')
weather = pd.read_excel("../2015 Freeman Ranch Weather Data.xlsx", sheet_name="Year2015", header=[0,1])
df_2 =  pd.read_csv('Life_Intake_Research_Placement_2015.csv')


df_2015

,TXSTDonorNumber,Curated,Current Facility,AgeAtDeath,Sex,Race,HispanicOrigin,Height(cm),HeightEstimated,CadaverStature(cm),...,LocationOfDeath,FacilityOfDeath,CityOfDeath,StateOfDeath,RecordEntryBy,RecordEntryDate,RecordAuditBy,RecordAuditDate,RecordUpdateBy,RecordUpdateDate
0,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
1,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
2,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
3,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,2015.065,True,GEFARL,59.0,Male,White,Non-hispanic,NaN,False,179.0,...,Other,2145 East Highway 80,Mesquite,TX,Import,7/20/2020,TLT,8/16/2020,NaN,NaN
91,2015.066,True,GEFARL,56.0,Female,White,Non-hispanic,170.0,False,165.0,...,Nursing home/Long Term Care Facility,Stonebriar Nursing & Rehab,Austin,TX,Import,7/20/2020,TLT,8/16/2020,NaN,NaN
92,2015.067,True,GEFARL,65.0,Female,White,Non-hispanic,173.0,False,175.0,...,Private residence,NaN,Floresville,TX,Import,7/20/2020,TLT,8/16/2020,NaN,NaN
93,2015.068,True,GEFARL,62.0,Male,White,Non-hispanic,178.0,False,168.0,...,Hospital inpatient,Methodist Stone Oak Hospital,San Antonio,TX,Import,7/20/2020,TLT,8/16/2020,NaN,NaN
94,2015.068,True,GEFARL,62.0,Male,White,Non-hispanic,178.0,False,168.0,...,Hospital inpatient,Methodist Stone Oak Hospital,San Antonio,TX,Import,7/20/2020,TLT,8/16/2020,NaN,NaN

In [3]:
df_2

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath,CityOfDeath,StateOfDeath,...,State,Donation.1,Curated,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,2015.001,59.0,2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center,Houston,TX,...,TX,NOK,Y,Surface,9/27/2018 brought to ORPL,NaN,NaN,NaN,NaN,NaN
1,2015.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TX,NOK,Y,Surface,9/27/2018 brought to ORPL,NaN,NaN,NaN,NaN,NaN
2,2015.002,82.0,2015-01-12,Actual,Closed head Injury (Due to fall),Accident,Hospital inpatient,University Hospital,San Antonio,TX,...,TX,NOK,Y,Freezer,Novem 2017 brought to ORPL,Curated Sept 2018,NaN,NaN,NaN,NaN
3,2015.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TX,NOK,Y,Freezer,Novem 2017 brought to ORPL,Curated Sept 2018,NaN,NaN,NaN,NaN
4,2015.003,85.0,2015-01-29,Actual,Asphyxia (1 day),Natural,Nursing home,Chisolm Trail Nursing and Rehabilitation Center,Lockhart,TX,...,TX,NOK,Y,Freezer,2/2018 brought to ORPL,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2015.067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TX,Living,Y,NIJ,1/26/2016 Surface~10:30am,4/24/2018 brought to ORPL,NaN,NaN,NaN,NaN
134,2015.068,62.0,2015-12-18,Actual,Hypoxic Respiratory Failure from End-Stage ALS,Natural,Hospital inpatient,Methodist Stone Oak Hospital,San Antonio,TX,...,TX,NOK,Y,12/22/2015 Surface ~1:15pm Long Decomp,NaN,NaN,NaN,NaN,NaN,NaN
135,2015.068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TX,NOK,Y,12/22/2015 Surface ~1:15pm Long Decomp,NaN,NaN,NaN,NaN,NaN,NaN
136,2015.069,58.0,2015-12-22,Actual,Neuroendocrine Carcinoma Metastasized to Liver,Natural,Private residence,NaN,San Antonio,TX,...,TX,NOK,NaN,1/1/2016 Burial ~3pm Vegitation,NaN,NaN,NaN,NaN,NaN,NaN
137,2015.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TX,NOK,NaN,1/1/2016 Burial ~3pm Vegitation,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
weather

      Unnamed: 0_level_0 Unnamed: 1_level_0  Temp    Hi   Low Out   Dew  Wind  \
                    Date               Time   Out  Temp  Temp Hum   Pt. Speed
0             2015-01-01           08:00:00  34.6  34.7  34.6  96  33.6     2
1             2015-01-01           08:30:00  34.7  34.7  34.6  96  33.7     2
2             2015-01-01           07:30:00  34.7  34.8  34.7  96  33.7     2
3             2015-01-01           07:00:00  34.7  34.9  34.7  96  33.7     3
4             2015-01-01           09:00:00  34.7  34.9  34.7  96  33.7     2
...                  ...                ...   ...   ...   ...  ..   ...   ...
16623         2015-12-31           22:00:00  48.9  49.1  48.9  74  41.0     7
16624         2015-12-31           22:30:00  48.9  48.9  48.8  74  41.0     7
16625         2015-12-31           23:00:00  48.7  48.9  48.7  75  41.1     8
16626         2015-12-31           23:30:00  48.6  48.8  48.6  74  40.7     7
16627         2016-01-01           00:00:00  48.3  48.7  48.3  74  40.4     8

                 ...  In   In               In Air     Wind       ISS  Arc.
       Dir  Run  ... Hum   Dew  Heat   EMC Density ET  Samp Tx  Recept Int.
0        N  1.0  ...  40  31.8  53.3  7.85  0.0775   0  703   1  100.0   30
1        N  1.0  ...  40  31.8  53.3  7.85  0.0775   0  702   1  100.0   30
2        N  1.0  ...  40  31.9  53.4  7.85  0.0775   0  702   1  100.0   30
3      NNE  1.5  ...  40  32.0  53.5  7.85  0.0775   0  703   1  100.0   30
4        N  1.0  ...  40  31.9  53.4  7.85  0.0775   0  703   1  100.0   30
...    ...  ...  ...  ..   ...   ...   ...     ...  ..  ...  ..    ...  ...
16623  NNE  3.5  ...  30  41.4  73.2  6.05  0.0746   0  702   1  100.0   30
16624  NNE  3.5  ...  30  42.3  74.5  6.05  0.0745   0  703   1  100.0   30
16625  NNE  4.0  ...  30  41.1  72.9  6.07  0.0747   0  702   1  100.0   30
16626  NNE  3.5  ...  29  41.4  74.5  5.85  0.0745   0  703   1  100.0   30
16627  NNE  4.0  ...  30  41.0  72.8  6.07  0.0747   0  702   1  100.0   30

[16628 rows x 38 columns]

In [5]:
# Combine the two header rows into one clear name
weather.columns = [
    f"{top.strip()}_{bot.strip()}".replace(" ", "_").replace(".", "").replace(",", "")
    for top, bot in weather.columns
]

# Manually clean a few obvious ones
rename = {
    "Date_Date": "date",
    "Time_Time": "time",
    "Out_Temp": "temp_out",
    "Hi_Temp": "temp_high",
    "Low_Temp": "temp_low",
    "Out_Hum": "humidity_out",
    "Dew_Pt": "dew_point",
    "Wind_Speed": "wind_speed",
    "Wind_Dir": "wind_dir",
    "Rain_Rain": "rain_total",
    "Rain_Rate": "rain_rate",
    "Solar_Rad": "solar_rad",
    "Solar_Energy": "solar_energy",
}
weather = weather.rename(columns=rename)
weather

,Unnamed:_0_level_0_Date,Unnamed:_1_level_0_Time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,In_Hum,In_Dew,In_Heat,In_EMC,In_Air_Density,In_Air_ET,Wind_Samp,Wind_Tx,ISS_Recept,Arc_Int
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,...,40,31.8,53.3,7.85,0.0775,0,703,1,100.0,30
1,2015-01-01,08:30:00,34.7,34.7,34.6,96,33.7,2,N,1.0,...,40,31.8,53.3,7.85,0.0775,0,702,1,100.0,30
2,2015-01-01,07:30:00,34.7,34.8,34.7,96,33.7,2,N,1.0,...,40,31.9,53.4,7.85,0.0775,0,702,1,100.0,30
3,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,...,40,32.0,53.5,7.85,0.0775,0,703,1,100.0,30
4,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,...,40,31.9,53.4,7.85,0.0775,0,703,1,100.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16623,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,...,30,41.4,73.2,6.05,0.0746,0,702,1,100.0,30
16624,2015-12-31,22:30:00,48.9,48.9,48.8,74,41.0,7,NNE,3.5,...,30,42.3,74.5,6.05,0.0745,0,703,1,100.0,30
16625,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,...,30,41.1,72.9,6.07,0.0747,0,702,1,100.0,30
16626,2015-12-31,23:30:00,48.6,48.8,48.6,74,40.7,7,NNE,3.5,...,29,41.4,74.5,5.85,0.0745,0,703,1,100.0,30
16627,2016-01-01,00:00:00,48.3,48.7,48.3,74,40.4,8,NNE,4.0,...,30,41.0,72.8,6.07,0.0747,0,702,1,100.0,30

In [6]:
rename = {
    "Unnamed:_0_level_0_Date": "date",
    "Unnamed:_1_level_0_Time": "time",
}
weather = weather.rename(columns=rename)
weather

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,In_Hum,In_Dew,In_Heat,In_EMC,In_Air_Density,In_Air_ET,Wind_Samp,Wind_Tx,ISS_Recept,Arc_Int
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,...,40,31.8,53.3,7.85,0.0775,0,703,1,100.0,30
1,2015-01-01,08:30:00,34.7,34.7,34.6,96,33.7,2,N,1.0,...,40,31.8,53.3,7.85,0.0775,0,702,1,100.0,30
2,2015-01-01,07:30:00,34.7,34.8,34.7,96,33.7,2,N,1.0,...,40,31.9,53.4,7.85,0.0775,0,702,1,100.0,30
3,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,...,40,32.0,53.5,7.85,0.0775,0,703,1,100.0,30
4,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,...,40,31.9,53.4,7.85,0.0775,0,703,1,100.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16623,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,...,30,41.4,73.2,6.05,0.0746,0,702,1,100.0,30
16624,2015-12-31,22:30:00,48.9,48.9,48.8,74,41.0,7,NNE,3.5,...,30,42.3,74.5,6.05,0.0745,0,703,1,100.0,30
16625,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,...,30,41.1,72.9,6.07,0.0747,0,702,1,100.0,30
16626,2015-12-31,23:30:00,48.6,48.8,48.6,74,40.7,7,NNE,3.5,...,29,41.4,74.5,5.85,0.0745,0,703,1,100.0,30
16627,2016-01-01,00:00:00,48.3,48.7,48.3,74,40.4,8,NNE,4.0,...,30,41.0,72.8,6.07,0.0747,0,702,1,100.0,30

In [7]:
df_hourly = weather[weather['time'].map(lambda t: t.minute) != 30].copy()
df_hourly

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,In_Hum,In_Dew,In_Heat,In_EMC,In_Air_Density,In_Air_ET,Wind_Samp,Wind_Tx,ISS_Recept,Arc_Int
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,...,40,31.8,53.3,7.85,0.0775,0,703,1,100.0,30
3,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,...,40,32.0,53.5,7.85,0.0775,0,703,1,100.0,30
4,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,...,40,31.9,53.4,7.85,0.0775,0,703,1,100.0,30
7,2015-01-01,06:00:00,35.2,35.3,34.9,95,33.9,2,NNE,1.0,...,40,32.1,53.6,7.85,0.0775,0,702,1,100.0,30
9,2015-01-01,05:00:00,35.1,35.4,35.1,95,33.8,2,WNW,1.0,...,39,31.5,53.6,7.65,0.0775,0,702,1,100.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16619,2015-12-31,20:00:00,49.5,49.7,49.5,75,41.9,7,NNE,3.5,...,30,41.7,73.7,6.05,0.0745,0,703,1,100.0,30
16621,2015-12-31,21:00:00,49.2,49.3,49.2,75,41.6,6,NNE,3.0,...,30,41.4,73.2,6.05,0.0747,0,703,1,100.0,30
16623,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,...,30,41.4,73.2,6.05,0.0746,0,702,1,100.0,30
16625,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,...,30,41.1,72.9,6.07,0.0747,0,702,1,100.0,30
16627,2016-01-01,00:00:00,48.3,48.7,48.3,74,40.4,8,NNE,4.0,...,30,41.0,72.8,6.07,0.0747,0,702,1,100.0,30

In [8]:
df_hourly.to_csv('FreemanRanchWeather2015_hourly_cleaned.csv')

In [9]:
mapping = pd.read_excel('../TXSTDSC Photo & Donor Data for Mapping.xlsx').drop(['??'], axis=1)
mapping['PhotoDate'] = pd.to_datetime(
    mapping['PhotoYear'].astype(str) + '-' +
    mapping['PhotoMonth'].astype(str) + '-' +
    mapping['PhotoDay'].astype(str),
    errors='coerce'
)
mapping.drop(columns=['PhotoYear', 'PhotoMonth', 'PhotoDay'], inplace=True)
mapping

,TXSTDonorNumber,TXST Donor Number Year,TXST Donor Number,PhotoType,PhotoDate
0,2015.001,2015,1,Intake,2015-01-09
1,2015.001,2015,1,Intake,2015-01-09
2,2015.001,2015,1,Intake,2015-01-09
3,2015.001,2015,1,Intake,2015-01-09
4,2015.001,2015,1,Intake,2015-01-09
...,...,...,...,...,...
287,2015.001,2015,1,Decomposition,2015-04-17
288,2015.001,2015,1,Disarticulation,2016-05-26
289,2015.001,2015,1,Disarticulation,2016-05-26
290,2015.001,2015,1,Disarticulation,2016-05-26
291,2015.001,2015,1,Disarticulation,2016-05-26

In [10]:
df_merged = df_hourly.merge(mapping, right_on='PhotoDate', left_on='date', how='inner').drop_duplicates()
df_merged

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,In_Air_ET,Wind_Samp,Wind_Tx,ISS_Recept,Arc_Int,TXSTDonorNumber,TXST Donor Number Year,TXST Donor Number,PhotoType,PhotoDate
0,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,0,702,1,100.0,30,2015.001,2015,1,Intake,2015-01-09
16,2015-01-09,01:00:00,37.3,37.3,36.9,62,25.5,1,SSW,0.5,...,0,702,1,100.0,30,2015.001,2015,1,Intake,2015-01-09
32,2015-01-09,02:00:00,37.7,37.7,37.5,63,26.2,0,NNE,0.0,...,0,702,1,100.0,30,2015.001,2015,1,Intake,2015-01-09
48,2015-01-09,03:00:00,37.7,37.7,37.5,65,27.0,0,NNE,0.0,...,0,702,1,100.0,30,2015.001,2015,1,Intake,2015-01-09
64,2015-01-09,04:00:00,37.6,37.7,37.6,65,26.9,1,ENE,0.5,...,0,702,1,100.0,30,2015.001,2015,1,Intake,2015-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6877,2015-04-17,19:00:00,66.7,66.7,65.9,96,65.5,1,W,0.5,...,0,703,1,100.0,30,2015.001,2015,1,Decomposition,2015-04-17
6884,2015-04-17,20:00:00,66.8,67.1,66.8,95,65.3,3,N,1.5,...,0,702,1,100.0,30,2015.001,2015,1,Decomposition,2015-04-17
6891,2015-04-17,21:00:00,65.8,66.2,65.8,95,64.3,5,NNE,2.5,...,0,702,1,100.0,30,2015.001,2015,1,Decomposition,2015-04-17
6898,2015-04-17,22:00:00,64.9,65.1,64.9,97,64.0,4,NNE,2.0,...,0,703,1,100.0,30,2015.001,2015,1,Decomposition,2015-04-17
6905,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,0,703,1,100.0,30,2015.001,2015,1,Decomposition,2015-04-17

In [11]:
df_complete = df_merged.merge(df_2015, on='TXSTDonorNumber', how='inner').drop_duplicates()
df_complete

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,LocationOfDeath,FacilityOfDeath,CityOfDeath,StateOfDeath,RecordEntryBy,RecordEntryDate,RecordAuditBy,RecordAuditDate,RecordUpdateBy,RecordUpdateDate
0,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
1,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
2,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
3,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4916,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4917,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4918,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4919,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN

In [12]:
# List the first three columns you want
first_cols = ['TXSTDonorNumber', 'date', 'time']

# Reorder the dataframe
df_complete = df_complete[first_cols + [col for col in df_complete.columns if col not in first_cols]]
df_complete

,TXSTDonorNumber,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,...,LocationOfDeath,FacilityOfDeath,CityOfDeath,StateOfDeath,RecordEntryBy,RecordEntryDate,RecordAuditBy,RecordAuditDate,RecordUpdateBy,RecordUpdateDate
0,2015.001,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
1,2015.001,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
2,2015.001,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
3,2015.001,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4,2015.001,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,2015.001,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4916,2015.001,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4917,2015.001,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4918,2015.001,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4919,2015.001,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN

In [13]:
df_complete = df_merged.merge(df_2015, on='TXSTDonorNumber', how='inner').drop_duplicates()
df_complete

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,...,LocationOfDeath,FacilityOfDeath,CityOfDeath,StateOfDeath,RecordEntryBy,RecordEntryDate,RecordAuditBy,RecordAuditDate,RecordUpdateBy,RecordUpdateDate
0,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
1,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
2,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
3,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4,2015-01-09,00:00:00,36.5,36.5,36.0,61,24.3,1,SSW,0.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4916,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4917,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4918,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN
4919,2015-04-17,23:00:00,66.0,66.0,65.4,98,65.4,3,NE,1.5,...,Hospital ER,Houston Northwest Medical Center,Houston,TX,Import,7/20/2020,TLT,7/31/2020,NaN,NaN

In [14]:
df_complete.to_csv('BioProfile_Destructive_Facts_Weather_2015.csv', index=False)