In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re
import numpy as np
pd.set_option("display.max_columns", None)

In [2]:
lif_int_res_pla = pd.read_csv('Life_Intake_Research_Placement.csv' )
bio_des_facts =  pd.read_csv('BioProfile_Destructive_Facts.csv')
weather = pd.read_csv('FreemanRanchWeather2015_hourly_cleaned.csv').drop('Unnamed: 0', axis=1)

In [3]:
paths = pd.read_csv('../filename_pmiClass.csv', dtype=str).drop(['year', 'second_year', 'day', 'month'], axis=1)
paths['TXSTDonorNumber'] = (
    paths['image_year'].astype(str) + '.' + paths['sample'].astype(str).str.zfill(3)
)
paths["TXSTDonorNumber"] = paths["TXSTDonorNumber"].astype("string")

print(paths.columns)
paths

Index(['filename', 'sample', 'picture_number', 'image_year', 'date',
       'PMI Class', 'TXSTDonorNumber'],
      dtype='object')

,filename,sample,picture_number,image_year,date,PMI Class,TXSTDonorNumber
0,2011.005.03.15.2011 (7).jpg,005,7,2011,3/15/2011,3,2011.005
1,2011.005.04.20.2011 (1).JPG,005,1,2011,4/20/2011,5,2011.005
2,2011.005.04.04.2011 (7).jpg,005,7,2011,4/4/2011,5,2011.005
3,2011.005.03.30.2011 (1).JPG,005,1,2011,3/30/2011,5,2011.005
4,2011.005.03.21.2011 (2).JPG,005,2,2011,3/21/2011,4,2011.005
...,...,...,...,...,...,...,...
500,2023.003.01.17.2023 (11).JPG,003,11,2023,1/17/2023,2,2023.003
501,2023.003.01.30.2023 (11).JPG,003,11,2023,1/30/2023,4,2023.003
502,2023.003.01.30.2024 (11).JPG,003,11,2023,1/30/2023,5,2023.003
503,2023.003.08.23.2023 (11).JPG,003,11,2023,8/23/2023,5,2023.003
504,2023.003.12.13.2023 (11).JPG,003,11,2023,12/13/2023,5,2023.003

In [4]:
donors = paths['TXSTDonorNumber'].astype(str).unique()
len(donors)

36

In [5]:
drop_cols = [
"In_Temp", "In_Hum",
"In_Dew", "In_Heat", "In_EMC", "In_Air_Density",
"In_Air_ET", "Wind_Samp", "Wind_Tx",   "ISS_Recept", 
"Researchers", "FactsOfDeathID", "CityOfDeath", "StateOfDeath",
"RecordEntryBy", "RecordEntryDate", "RecordAuditBy", "RecordAuditDate",
"RecordUpdateBy", "RecordUpdateDate"]
dfs = {
    "lif_int_res_pla": lif_int_res_pla,
    "bio_des_facts": bio_des_facts,
    "weather": weather,
}

for name, df_ in dfs.items():
    cols_to_drop = [c for c in drop_cols if c in df_.columns]
    df_.drop(columns=cols_to_drop, inplace=True)
    print(name, "dropped:", cols_to_drop)

lif_int_res_pla dropped: ['CityOfDeath', 'StateOfDeath', 'RecordEntryBy', 'RecordEntryDate', 'RecordAuditBy', 'RecordAuditDate', 'RecordUpdateBy', 'RecordUpdateDate']
bio_des_facts dropped: ['Researchers', 'FactsOfDeathID', 'CityOfDeath', 'StateOfDeath', 'RecordEntryBy', 'RecordEntryDate', 'RecordAuditBy', 'RecordAuditDate', 'RecordUpdateBy', 'RecordUpdateDate']
weather dropped: ['In_Temp', 'In_Hum', 'In_Dew', 'In_Heat', 'In_EMC', 'In_Air_Density', 'In_Air_ET', 'Wind_Samp', 'Wind_Tx', 'ISS_Recept']

In [6]:
mask = (weather == '---').all(axis=0)   # True for cols that are all '---'
weather = weather.loc[:, ~mask]
weather

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,Hi_Speed,Hi_Dir,Wind_Chill,Heat_Index,THW_Index,THSW_Bar,THSW_Rain,rain_rate,Heat_D-D,Cool_D-D,Arc_Int
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,6,NNE,33.8,34.6,33.8,30.300,0.01,0.00,0.633,0.0,30
1,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,9,N,32.4,34.7,32.4,30.303,0.02,0.06,0.631,0.0,30
2,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,7,NNE,33.9,34.7,33.9,30.315,0.00,0.00,0.631,0.0,30
3,2015-01-01,06:00:00,35.2,35.3,34.9,95,33.9,2,NNE,1.0,7,NNE,34.5,35.2,34.5,30.305,0.00,0.00,0.621,0.0,30
4,2015-01-01,05:00:00,35.1,35.4,35.1,95,33.8,2,WNW,1.0,6,NNW,34.4,35.1,34.4,30.318,0.04,0.11,0.623,0.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8309,2015-12-31,20:00:00,49.5,49.7,49.5,75,41.9,7,NNE,3.5,14,NE,46.6,49.3,46.4,30.325,0.00,0.00,0.323,0.0,30
8310,2015-12-31,21:00:00,49.2,49.3,49.2,75,41.6,6,NNE,3.0,15,NNE,46.7,48.9,46.4,30.351,0.00,0.00,0.329,0.0,30
8311,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,13,NE,45.9,48.6,45.6,30.344,0.00,0.00,0.335,0.0,30
8312,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,16,N,44.9,48.4,44.6,30.344,0.00,0.00,0.340,0.0,30
8313,2016-01-01,00:00:00,48.3,48.7,48.3,74,40.4,8,NNE,4.0,15,NNE,44.5,48.0,44.2,30.337,0.00,0.00,0.348,0.0,30

In [7]:
weather = weather.copy()

weather["date"] = pd.to_datetime(weather["date"], errors="coerce")

m = weather["date"].dt.month
season_num = (m % 12 + 3) // 3
season_map = {1: "Winter", 2: "Spring", 3: "Summer", 4: "Autumn"}
weather["season"] = season_num.map(season_map)
weather

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,Hi_Speed,Hi_Dir,Wind_Chill,Heat_Index,THW_Index,THSW_Bar,THSW_Rain,rain_rate,Heat_D-D,Cool_D-D,Arc_Int,season
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,6,NNE,33.8,34.6,33.8,30.300,0.01,0.00,0.633,0.0,30,Winter
1,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,9,N,32.4,34.7,32.4,30.303,0.02,0.06,0.631,0.0,30,Winter
2,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,7,NNE,33.9,34.7,33.9,30.315,0.00,0.00,0.631,0.0,30,Winter
3,2015-01-01,06:00:00,35.2,35.3,34.9,95,33.9,2,NNE,1.0,7,NNE,34.5,35.2,34.5,30.305,0.00,0.00,0.621,0.0,30,Winter
4,2015-01-01,05:00:00,35.1,35.4,35.1,95,33.8,2,WNW,1.0,6,NNW,34.4,35.1,34.4,30.318,0.04,0.11,0.623,0.0,30,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8309,2015-12-31,20:00:00,49.5,49.7,49.5,75,41.9,7,NNE,3.5,14,NE,46.6,49.3,46.4,30.325,0.00,0.00,0.323,0.0,30,Winter
8310,2015-12-31,21:00:00,49.2,49.3,49.2,75,41.6,6,NNE,3.0,15,NNE,46.7,48.9,46.4,30.351,0.00,0.00,0.329,0.0,30,Winter
8311,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,13,NE,45.9,48.6,45.6,30.344,0.00,0.00,0.335,0.0,30,Winter
8312,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,16,N,44.9,48.4,44.6,30.344,0.00,0.00,0.340,0.0,30,Winter
8313,2016-01-01,00:00:00,48.3,48.7,48.3,74,40.4,8,NNE,4.0,15,NNE,44.5,48.0,44.2,30.337,0.00,0.00,0.348,0.0,30,Winter

In [8]:
years = [2011, 2012, 2013, 2014, 2015, 2023]

# filter by year
weather_filtered = weather[weather["date"].dt.year.isin(years)]
weather_filtered

,date,time,Temp_Out,temp_high,temp_low,humidity_out,dew_point,wind_speed,wind_dir,Wind_Run,Hi_Speed,Hi_Dir,Wind_Chill,Heat_Index,THW_Index,THSW_Bar,THSW_Rain,rain_rate,Heat_D-D,Cool_D-D,Arc_Int,season
0,2015-01-01,08:00:00,34.6,34.7,34.6,96,33.6,2,N,1.0,6,NNE,33.8,34.6,33.8,30.300,0.01,0.00,0.633,0.0,30,Winter
1,2015-01-01,07:00:00,34.7,34.9,34.7,96,33.7,3,NNE,1.5,9,N,32.4,34.7,32.4,30.303,0.02,0.06,0.631,0.0,30,Winter
2,2015-01-01,09:00:00,34.7,34.9,34.7,96,33.7,2,N,1.0,7,NNE,33.9,34.7,33.9,30.315,0.00,0.00,0.631,0.0,30,Winter
3,2015-01-01,06:00:00,35.2,35.3,34.9,95,33.9,2,NNE,1.0,7,NNE,34.5,35.2,34.5,30.305,0.00,0.00,0.621,0.0,30,Winter
4,2015-01-01,05:00:00,35.1,35.4,35.1,95,33.8,2,WNW,1.0,6,NNW,34.4,35.1,34.4,30.318,0.04,0.11,0.623,0.0,30,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8308,2015-12-31,19:00:00,49.7,49.8,49.7,74,41.7,6,NNE,3.0,10,NNE,47.3,49.4,47.0,30.301,0.00,0.00,0.319,0.0,30,Winter
8309,2015-12-31,20:00:00,49.5,49.7,49.5,75,41.9,7,NNE,3.5,14,NE,46.6,49.3,46.4,30.325,0.00,0.00,0.323,0.0,30,Winter
8310,2015-12-31,21:00:00,49.2,49.3,49.2,75,41.6,6,NNE,3.0,15,NNE,46.7,48.9,46.4,30.351,0.00,0.00,0.329,0.0,30,Winter
8311,2015-12-31,22:00:00,48.9,49.1,48.9,74,41.0,7,NNE,3.5,13,NE,45.9,48.6,45.6,30.344,0.00,0.00,0.335,0.0,30,Winter
8312,2015-12-31,23:00:00,48.7,48.9,48.7,75,41.1,8,NNE,4.0,16,N,44.9,48.4,44.6,30.344,0.00,0.00,0.340,0.0,30,Winter

In [9]:
weather_filtered.to_csv('FreemanRanchWeather_cleaned.csv', index=False)

In [10]:
missing_pct = lif_int_res_pla.isna().mean()

cols_to_drop = missing_pct[missing_pct > 0.70].index
print(cols_to_drop)
lif_int_res_pla = lif_int_res_pla.drop(columns=cols_to_drop)

Index(['WaistCircumference(cm)', 'DonatedBy', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [11]:
missing = bio_des_facts.isna().mean()

cols_to_drop = missing[missing > 0.70].index
print(cols_to_drop)
bio_des_facts = bio_des_facts.drop(columns=cols_to_drop)

Index([], dtype='object')

In [12]:
# Make sure the donor number columns are strings before filter
lif_int_res_pla['TXSTDonorNumber'] = lif_int_res_pla['TXSTDonorNumber'].astype(str)
bio_des_facts['TXSTDonorNumber']   = bio_des_facts['TXSTDonorNumber'].astype(str)

# Filter the DataFrames
lif_int_res_pla_filt = lif_int_res_pla[
    lif_int_res_pla['TXSTDonorNumber'].isin(donors)
]

bio_des_facts_filt = bio_des_facts[
    bio_des_facts['TXSTDonorNumber'].isin(donors)
]

In [13]:
def drop_mostly_missing_rows(df, pct_missing=0.9):
    # keep rows that have at least (1 - pct_missing) non-null values
    thresh = int((1 - pct_missing) * df.shape[1])
    return df.dropna(thresh=thresh)

lif_int_res_pla = drop_mostly_missing_rows(lif_int_res_pla_filt, pct_missing=0.7)
bio_des_facts   = drop_mostly_missing_rows(bio_des_facts_filt,   pct_missing=0.7)
weather         = drop_mostly_missing_rows(weather,         pct_missing=0.7)

In [14]:
print(lif_int_res_pla.shape)
lif_int_res_pla.columns

(45, 57)

Index(['TXSTDonorNumber', 'AgeAtDeath', 'DateOfDeath', 'DODSpecify',
       'ImmediateCOD', 'MannerOfDeath', 'LocationOfDeath', 'FacilityOfDeath',
       'IntakeID', 'DateReceived', 'DateOfIntake', 'InitialPlacementLocation',
       'ApproxTime', 'CadaverStature(cm)', 'FootLength(cm)',
       'CadaverWeight(lbs)', 'PersonalEffects', 'PersonalEffectsDescription',
       'SamplesCollected', 'PhotographID', 'PhotographOverallBody',
       'PhotographAnteriorFace', 'PhotographProfileLeftFace',
       'PhotographProfileRightFace', 'PhotographTeeth', 'PhotographLeftArm',
       'PhotographRightArm', 'PhotographLeftLeg', 'PhotographRightLeg',
       'PhotographScars', 'PhotographTattoos', 'PhotographInjuries',
       'PhotographJewelry', 'Autopsy', 'FullAutopsy', 'AbdominalAutopsy',
       'CranialAutopsy', 'ThoracicAutopsy', 'SpinalAutopsy', 'OrganDonor',
       'DonatedEyes', 'DonatedSkin', 'DonatedBones', 'DonatedInternalOrgans',
       'Paperless', 'Donation', 'TXSTDSC #', 'DOD', 'Received by FACTS',
       'Initial Placement', 'Length', 'Place of death', 'State', 'Donation.1',
       'Curated', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [15]:
lif_int_res_pla

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath,IntakeID,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),FootLength(cm),CadaverWeight(lbs),PersonalEffects,PersonalEffectsDescription,SamplesCollected,PhotographID,PhotographOverallBody,PhotographAnteriorFace,PhotographProfileLeftFace,PhotographProfileRightFace,PhotographTeeth,PhotographLeftArm,PhotographRightArm,PhotographLeftLeg,PhotographRightLeg,PhotographScars,PhotographTattoos,PhotographInjuries,PhotographJewelry,Autopsy,FullAutopsy,AbdominalAutopsy,CranialAutopsy,ThoracicAutopsy,SpinalAutopsy,OrganDonor,DonatedEyes,DonatedSkin,DonatedBones,DonatedInternalOrgans,Paperless,Donation,TXSTDSC #,DOD,Received by FACTS,Initial Placement,Length,Place of death,State,Donation.1,Curated,Unnamed: 10,Unnamed: 11
36,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated
39,2011.008,53,2011-06-08,NaN,Lung cancer,Natural,Hospital inpatient,Christus Santa Rosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D08-2011,2011.008,2011-06-08 00:00:00,2011-06-09 00:00:00,Surface,1,"New Braunfels, TX",TX,NOK,Y,3/30/2012 buried,10/21/12 excavated
40,2011.008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,2011-06-09,2011-06-09,Surface,1218.0,173.0,23,NaN,%,NaN,%,False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D08-2011,2011.008,2011-06-08 00:00:00,2011-06-09 00:00:00,Surface,1,"New Braunfels, TX",TX,NOK,Y,3/30/2012 buried,10/21/12 excavated
43,2011.011,75,2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN,91.0,2011-07-19,2011-07-19,NaN,NaN,173.0,NaN,NaN,Z,NaN,Z,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,NaN,False,False,False,False,False,D11-2011,2011.011,2011-07-18 00:00:00,2011-07-19 00:00:00,Surface,1,"Llano, TX",TX,Living,Y,1/2/2012 buried,3/25/2012 excavated
55,2011.023,66,2011-12-18,NaN,End Stage renal disease,Natural,Nursing home,Guadalupe Valley Nursing Center LP,118.0,2011-12-19,2011-12-19,Surface,NaN,163.0,22.5,NaN,q,NaN,q,True,True,True,False,False,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D23-2011,2011.023,2011-12-18 00:00:00,2011-12-19 00:00:00,Surface,1,"Seguin, TX",TX,Living,Y,1/16/2013 Picked up and placed in cage @ FARF,1/17/2013 brought to ORPL
59,2012.002,68,2012-01-06,NaN,PAI Respiratory Failure (Acute),Natural,Hospital inpatient,St. Lukes Patients Medical Center,120.0,2012-01-06,2012-01-06,Surface,NaN,154.0,23,NaN,s,NaN,s,True,True,True,False,False,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D02-2012,2012.002,2012-01-06 00:00:00,2012-01-06 00:00:00,Surface,0,"Pasadena, TX",TX,NOK,Y,2/1/13 picked up and in bin @farf,5/19/13 buried
60,2012.003,78,2012-01-27,NaN,Metastatic Lung Cancer,Natural,Hospital inpatient,"Llano Memorial Healthcare System, Memorial Hos...",121.0,2012-01-28,2012-01-28,Surface,NaN,158.0,21,NaN,t,"hospital gown, bible",t,True,True,True,False,False,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D03-2012,2012.003,2012-01-27 00:00:00,2012-01-28 00:00:00,Surface,1,"Llano, TX",TX,Living,Y,6/15/12 buried,4/2014 Curated
61,2012.004,63,2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital,122.0,2012-01-28,2012-01-28,Surface,NaN,160.0,22,NaN,u,NaN,u,True,True,True,False,False,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D04-2012,2012.004,2012-01-27 00:00:00,2012-01-28 00:00:00,Surface,1,"Temple, TX",TX,Living,Y,11/08/2012 picked up and @ ORPL,Curated 11/2013
66,2012.009,88,2012-03-25,Actual,NaN,NaN,Private residence,NaN,145.0,2012-03-26,2012-03-26,Surface,NaN,165.0,24,NaN,,1 white t-shirt,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D09-2012,2012.009,2012-03-25 00:00:00,2012-03-26 00:00:00,Surface,1,"Cuero, TX",TX,Living,Y,5/23/2012 Buried,Curated 9/30/2013
68,2012.011,76,2012-03-30,Actual,Respiratory arrest,Natural,Hospital inpatient,Central Texas Medical Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D11-2012,2012.011,2012-03-30 00:00:00,2012-03-30 00:00:00,Surface,0,"San Marcos, TX",TX,NOK,Y,1/16/2013 Picked up and placed in cage @ FARF,1/17/2013 brought to ORPL
69,2012.011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147.0,2012-03-30,2012-03-30,Surface,NaN,170.0,23,NaN,,NaN,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D11-2012,2012.011,2012-03-30 00:00:00,2012-03-30 00:00:00,Surface,0,"San Marcos, TX",TX,NOK,Y,1/16/2013 Picked up and placed in cage @ FARF,1/17/2013 brought to ORPL
70,2012.012,64,2012-04-10,Actual,Lung Cancer,Natural,Nursing home,Blanco Villa Nursing and Rehabilitation LP,148.0,2012-04-10,2012-04-10,Surface,NaN,159.0,22,NaN,,removed,,True,True,True,True,True,True,True,True,True,True,False,False,False,True,No,False,False,False,False,False,No,False,False,False,False,False,D12-2012,2012.012,2012-04-10 00:00:00,2012-04-10 00:00:00,Surface,0,"San Antonio, TX",TX,Living,Y,5/31/2012 Buried,7/2014 Curated
72,2012.014,85,2012-04-30,Actual,Failure to thrive,Natural,Nursing home,Gracy Woods II Living Center,150.0,2012-04-30,2012-04-30,Surface,NaN,166.0,26,NaN,,NaN,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D14-2012,2012.014,2012-04-30 00:00:00,2012-04-30 00:00:00,Surface,0,"Austin, TX",TX,NOK,Y,9/25/2012 Picked up and placed in cage at FARF,9/30/2013 Curated
73,2012.015,62,2012-05-07,Actual,Small cell lung cancer,Natural,Hospice facility,Christopher House,151.0,2012-05-07,2012-05-07,Surface,NaN,181.0,25,NaN,,removed and sent to family via mail,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D15-2012,2012.015,2012-05-07 00:00:00,2012-05-07 00:00:00,Surface,0,"Austin, TX",TX,NOK,Y,7/31/2012 Picked up and brought to ORPL,11/7/2012 Curated
81,2012.023,56,2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D23-2012,2012.023,2012-06-16 00:00:00,2012-06-17 00:00:00,Cooler,1,Corpus Christi,TX,Living,Y,6/18/2012 placed on surface,9/20/2012 Picked up and brought to ORPL
82,2012.023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,159.0,2012-06-17,2012-06-17,Surface,NaN,181.0,25,NaN,,NaN,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D23-2012,2012.023,2012-06-16 00:00:00,2012-06-17 00:00:00,Cooler,1,Corpus Christi,TX,Living,Y,6/18/2012 placed on surface,9/20/2012 Picked up and brought to ORPL
83,2012.024,83,2012-06-21,Actual,Metastatic renal cell carcinoma,Natural,Nursing home,Westminster,160.0,2012-06-21,2012-06-21,Surface,NaN,152.0,21,NaN,,Removed,,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D24-2012,2012.024,2012-06-21 00:00:00,2012-06-21 00:00:00,Surface,0,"Austin, TX",TX,NOK,Y,7/31/2012 Picked up and brought to ORPL,Curated
88,2012.029,68,2012-07-13,Actual,Ischemic cardiomyopathy,Natural,Hospice facility,Christopher House,165.0,2012-07-13,2012-07-13,Surface,NaN,170.0,25,NaN,,Removed,,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D29-2012,2012.029,2012-07-13 00:00:00,2012-07-13 00:00:00,Surface,0,"Austin, TX",TX,Living,Y,Curated 10/2013,NaN
130,2013.014,58,2013-02-19,Actual,Ischemic stroke,Natural,Hospice facility,Christopher House,216.0,2013-02-19,2013-02-19,Surface,NaN,164.0,23,NaN,Ï,NaN,Ï,False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D14-2013,2013.014,2013-02-19 00:00:00,2012-02-19 00:00:00,Surface,0,"Austin, TX",TX,NOK,Y,NaN,NaN
141,2013.023,63,2013-05-05,Actual,Renal Cell Carcinoma with Metastases to liver ...,Natural,Nursing home,Indian Oaks,225.0,2013-05-06,2013-05-06,Surface,1652.0,175.0,25,NaN,Ø,NaN,Ø,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D23-2013,2013.023,2013-05-05 00:00:00,2013-05-06 00:00:00,surface ~ 4:52pm,1,"Kileen, TX",TX,Living,Y,NaN,Curated March 2015
162,2013.041,76,2013-07-26,NaN,Metastatic Rectal Cancer,Natural,Private residence,NaN,243.0,2013-07-26,2013-07-26,Surface,1300.0,164.0,22,NaN,ê,Removed,ê,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D41-2013,2013.041,2013-07-26 00:00:00,2013-07-26 00:00:00,Surface ~1pm,0,"Austin, tX",TX,NOK,Y,"HANDS AND FEET AT orpl, DONATION IN 22",NaN
189,2014.001,72,2013-12-27,Actual,Sepsis,Natural,Hospital inpatient,Guadalupe Regional Medical Center,268.0,2014-01-07,NaN,Cooler,1700.0,144.0,21.5,NaN,ă,NaN,ă,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D01-2014,2014.001,2013-12-27 00:00:00,2014-01-07 00:00:00,Cooler~5pm,11,"Seguin, TX",TX,NOK,Y,1/10/2014 ~11am Surface,Curated November 2016
190,2014.002,64,2014-01-10,NaN,Pulmonary thromboemboli,Natural,Private residence,NaN,269.0,2014-01-21,NaN,Cooler,1440.0,165.0,22,NaN,Ą,Green blood-stained shirt,Ą,True,True,True,True,True,True,True,True,True,True,True,False,False,False,Yes,True,False,False,False,False,Yes,False,True,True,False,False,D02-2014,2014.002,2014-01-10 00:00:00,2014-01-21 00:00:00,Cooler,11,"Houston, TX",TX,NOK,Y,1/30/2014 ~2pm Surface,Curated November 2016
194,2014.006,73,2014-02-10,Actual,Lung Cancer,Natural,Nursing home,Legend Oaks healthcare and Rehabilitation- Kyle,273.0,2014-02-10,2014-02-10,Surface,1613.0,170.0,NaN,NaN,Ĉ,NaN,Ĉ,False,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D06-2014,2014.006,2014-02-10 00:00:00,2014-02-10 00:00:00,Surface ~4:30pm,0,"Kyle, TX",TX,Living,Y,Curated,NaN
200,2014.012,64,2014-03-04,Actual,Acute Cerebrovascular Accident,Natural,Hospital inpatient,South Austin Hospital,279.0,2014-03-05,2014-03-05,Surface,1800.0,168.0,25,NaN,Ď,NaN,Ď,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D12-2014,2014.012,2014-03-04 00:00:00,2014-03-05 00:00:00,Surface~5pm,1,"Austin, TX",TX,NOK,Y,Curated April 2017,NaN
203,2014.014,78,2014-02-26,NaN,Arteriosclerotic Cardiovascular Disease,Natural,Private residence,NaN,282.0,2014-03-10,2014-03-10,Surface,1900.0,172.0,25,NaN,đ,Removed,đ,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D14-2014,2014.014,2014-02-26 00:00:00,2014-03-10 00:00:00,Surface~7pm,14,"Collin Co., TX",TX,NOK,Y,Curated April 2017,NaN
206,2014.016,59,2014-03-13,Actual,Late effects of lung cancer probably bronchoge...,Natural,Nursing home,Colonial Manor Care Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D16-2014,2014.016,2014-03-13 00:00:00,2014-03-14 00:00:00,Surface~11:30,1,"New Braunfels, TX",TX,Living,Y,September 2015 Curated,NaN
207,2014.016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,284.0,2014-03-14,2014-03-14,Surface,1130.0,164.0,24,NaN,ē,Removed,ē,False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D16-2014,2014.016,2014-03-13 00:00:00,2014-03-14 00:00:00,Surface~11:30,1,"New Braunfels, TX",TX,Living,Y,September 2015 Curated,NaN
262,2014.044,73,2014-08-31,NaN,Lung Adenocarcinoma metastatic to Brain and Bone,Natural,Hospice facility,Christopher House,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D44-2014,2014.044,2014-08-31 00:00:00,2014-09-01 00:00:00,Surface~13:30,1,"Austin, TX",TX,Living,Y,Curated June 2016,NaN
263,2014.044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312.0,2014-09-01,2014-09-01,Surface,1330.0,167.0,25,NaN,į,NaN,į,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D44-2014,2014.044,2014-08-31 00:00:00,2014-09-01 00:00:00,Surface~13:30,1,"Austin, TX",TX,Living,Y,Curated June 2016,NaN
310,2014.068,84,2014-12-04,Actual,Hypoxemic Respiratory Failure,Natural,Hospital inpatient,St. David's Medical Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D68-2014,2014.068,2014-12-04 00:00:00,2014-12-05 00:00:00,Surface ~5:20pm,1,"Austin, TX",TX,NOK,Y,ORPL 10/2017,NaN
311,2014.068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336.0,2014-12-05,2014-12-05,Surface,1720.0,170.0,25.5,NaN,Ň,Hospital clothing,Ň,True,True,True,True,True,True,True,True,True,True,False,False,True,False,No,False,False,False,False,False,No,False,False,False,False,False,D68-2014,2014.068,2014-12-04 00:00:00,2014-12-05 00:00:00,Surface ~5:20pm,1,"Austin, TX",TX,NOK,Y,ORPL 10/2017,NaN
312,2015.001,59,2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D01-2015,2015.001,2015-01-05 00:00:00,2015-01-09 00:00:00,Freezer~8:35pm,4,"Houston, TX",TX,NOK,Y,Surface,9/27/2018 brought to ORPL
313,2015.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,337.0,2015-01-09,NaN,Cooler,2035.0,179.0,25,NaN,ň,NaN,ň,True,True,True,True,True,True,True,True,True,True,False,False,True,False,Yes,True,False,False,False,False,No,False,False,False,False,False,D01-2015,2015.001,2015-01-05 00:00:00,2015-01-09 00:00:00,Freezer~8:35pm,4,"Houston, TX",TX,NOK,Y,Surface,9/27/2018 brought to ORPL
314,2015.002,82,2015-01-12,Actual,Closed head Injury (Due to fall),Accident,Hospital inpatient,University Hospital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D02-2015,2015.002,2015-01-12 00:00:00,2015-01-15 00:00:00,Cooler~1:12pm,3,"San Antonio, TX",TX,NOK,Y,Freezer,Novem 2017 brought to ORPL
315,2015.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.0,2015-01-15,2015-01-15,Cooler,1312.0,172.0,25,NaN,ŉ,NaN,ŉ,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D02-2015,2015.002,2015-01-12 00:00:00,2015-01-15 00:00:00,Cooler~1:12pm,3,"San Antonio, TX",TX,NOK,Y,Freezer,Novem 2017 brought to ORPL
316,2015.003,85,2015-01-29,Actual,Asphyxia (1 day),Natural,Nursing home,Chisolm Trail Nursing and Rehabilitation Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D03-2015,2015.003,2015-01-29 00:00:00,2015-01-29 00:00:00,Freezer~5:05pm,0,"Lockhart, TX",TX,NOK,Y,Freezer,2/2018 brought to ORPL
317,2015.003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,339.0,2015-01-29,NaN,Freezer,1705.0,167.0,25,NaN,Ŋ,NaN,Ŋ,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D03-2015,2015.003,2015-01-29 00:00:00,2015-01-29 00:00:00,Freezer~5:05pm,0,"Lockhart, TX",TX,NOK,Y,Freezer,2/2018 brought to ORPL
326,2015.008,51,2015-02-14,Actual,Small cell carcinoma of the lung with nodal me...,Natural,Hospice facility,Christopher House,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D08-2015,2015.008,2015-02-14 00:00:00,2015-02-15 00:00:00,surface ~1:10pm,1,"Pflugerville, TX",TX,Living,Y,Curated October 2016,NaN
327,2015.008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344.0,2015-02-15,2015-02-15,Surface,1310.0,176.0,26,NaN,ŏ,NaN,ŏ,True,True,True,True,True,True,True,True,True,True,True,True,False,False,No,False,False,False,False,False,NaN,False,False,False,False,False,D08-2015,2015.008,2015-02-14 00:00:00,2015-02-15 00:00:00,surface ~1:10pm,1,"Pflugerville, TX",TX,Living,Y,Curated October 2016,NaN
328,2015.009,74,2015-02-25,Actual,cardiac arrest,Natural,Hospital inpatient,Heart Hospital of Austin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D09-2015,2015.009,2015-02-26 00:00:00,2015-02-26 00:00:00,surface~6pm,0,"Austin, TX",TX,Living,Y,10/4/2018 brought remains to ORPL,NaN
329,2015.009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345.0,2015-02-26,2015-02-26,Surface,1800.0,158.0,21,NaN,Ő,"""remain on body""",Ő,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D09-2015,2015.009,2015-02-26 00:00:00,2015-02-26 00:00:00,surface~6pm,0,"Austin, TX",TX,Living,Y,10/4/2018 brought remains to ORPL,NaN
1246,2023.001,74,2023-01-04,Actual,"Amyotrophic lateral sclerosis, bulbar onset",Natural,Nursing home/Long Term Care Facility,Bandera Health and Rehabilitation Center,804.0,2023-01-05,2023-01-05,Cooler,1635.0,150.0,23,87.0,̛,NaN,̛,True,True,True,True,True,True,True,True,True,True,True,True,True,True,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.001,2023-01-04 00:00:00,2023-01-05 00:00:00,cooler @1635,1,"Bandera, TX",TX,Living,NaN,Gocha Xray NIJ,NaN
1247,2023.002,73,2023-01-03,Actual,Colon cancer metastatic to liver,Natural,Private residence,8904 Linton Dr.,805.0,2023-01-06,2023-01-06,Cooler,1600.0,172.0,25,177.0,̜,"Diaper, orange bedsheet, orange pillow",̜,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.002,2023-01-03 00:00:00,2023-01-06 00:00:00,cooler @1600,3,"Austin, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN
1248,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN

In [16]:
print(bio_des_facts.shape)
bio_des_facts.columns

(51, 23)

Index(['TXSTDonorNumber', 'Curated', 'Current Facility', 'AgeAtDeath', 'Sex',
       'Race', 'HispanicOrigin', 'Height(cm)', 'HeightEstimated',
       'CadaverStature(cm)', 'Weight(lb)', 'WeightEstimated',
       'CadaverWeight(lbs)', 'Destructive Sampling', 'SamplingType',
       'ElementsSampled', 'SpecifySamples', 'DateOfDeath', 'DODSpecify',
       'ImmediateCOD', 'MannerOfDeath', 'LocationOfDeath', 'FacilityOfDeath'],
      dtype='object')

In [17]:
bio_des_facts

,TXSTDonorNumber,Curated,Current Facility,AgeAtDeath,Sex,Race,HispanicOrigin,Height(cm),HeightEstimated,CadaverStature(cm),Weight(lb),WeightEstimated,CadaverWeight(lbs),Destructive Sampling,SamplingType,ElementsSampled,SpecifySamples,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath
63,2011.005,True,GEFARL,80.0,Male,White,Non-hispanic,178.0,True,178.0,160.0,True,NaN,True,6831,6831,Left 6th rib midshaft,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN
73,2011.011,True,GEFARL,75.0,Male,White,NaN,NaN,False,173.0,218.0,False,NaN,True,91,91,"Occipital, mandible, left and right: 6th rib, ...",2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN
74,2011.011,True,GEFARL,75.0,Male,White,NaN,NaN,False,173.0,218.0,False,NaN,True,6834,6834,Left 5th rib midshaft,2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN
75,2011.011,True,GEFARL,75.0,Male,White,NaN,NaN,False,173.0,218.0,False,NaN,True,9254,9254,2.5 cm cortical bone fragment taken from the d...,2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN
89,2012.002,True,GEFARL,68.0,Female,White,Non-hispanic,157.0,False,154.0,130.0,True,NaN,True,6855,6855,Left 6th rib midshaft,2012-01-06,NaN,PAI Respiratory Failure (Acute),Natural,Hospital inpatient,St. Lukes Patients Medical Center
90,2012.003,True,GEFARL,78.0,Female,White,Non-hispanic,163.0,True,158.0,125.0,True,NaN,True,92,92,"Teeth #3 and #27, occipital, mandible, left an...",2012-01-27,NaN,Metastatic Lung Cancer,Natural,Hospital inpatient,"Llano Memorial Healthcare System, Memorial Hos..."
91,2012.003,True,GEFARL,78.0,Female,White,Non-hispanic,163.0,True,158.0,125.0,True,NaN,True,248,248,"Tooth #4, left rib 7",2012-01-27,NaN,Metastatic Lung Cancer,Natural,Hospital inpatient,"Llano Memorial Healthcare System, Memorial Hos..."
92,2012.003,True,GEFARL,78.0,Female,White,Non-hispanic,163.0,True,158.0,125.0,True,NaN,True,9273,9273,2.5 cm cortical bone fragment taken from the d...,2012-01-27,NaN,Metastatic Lung Cancer,Natural,Hospital inpatient,"Llano Memorial Healthcare System, Memorial Hos..."
93,2012.004,True,GEFARL,63.0,Female,White,Non-hispanic,168.0,False,160.0,154.0,False,NaN,True,93,93,"Teeth #5 and #20, occipital, mandible, left an...",2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital
94,2012.004,True,GEFARL,63.0,Female,White,Non-hispanic,168.0,False,160.0,154.0,False,NaN,True,221,221,Tooth #26,2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital
95,2012.004,True,GEFARL,63.0,Female,White,Non-hispanic,168.0,False,160.0,154.0,False,NaN,True,6856,6856,Left 5th rib midshaft,2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital
96,2012.004,True,GEFARL,63.0,Female,White,Non-hispanic,168.0,False,160.0,154.0,False,NaN,True,9255,9255,2.5 cm cortical bone fragment taken from the d...,2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital
97,2012.004,True,GEFARL,63.0,Female,White,Non-hispanic,168.0,False,160.0,154.0,False,NaN,True,19925,19925,Tooth 11,2012-01-27,NaN,Metastatic Breast Cancer,Natural,Hospital inpatient,Scott and White Memorial Hospital
103,2012.009,True,GEFARL,88.0,Male,Black or African American,Non-hispanic,168.0,True,165.0,140.0,False,NaN,True,6847,6847,Left 6th rib midshaft,2012-03-25,Actual,NaN,NaN,Private residence,NaN
105,2012.011,True,GEFARL,76.0,Male,Hispanic,NaN,180.0,False,170.0,220.0,True,NaN,True,6849,6849,Left 6th rib midshaft,2012-03-30,Actual,Respiratory arrest,Natural,Hospital inpatient,Central Texas Medical Center
106,2012.012,True,GEFARL,64.0,Female,White,Non-hispanic,163.0,False,159.0,120.0,True,NaN,True,6850,6850,Left 6th rib midshaft,2012-04-10,Actual,Lung Cancer,Natural,Nursing home,Blanco Villa Nursing and Rehabilitation LP
107,2012.012,True,GEFARL,64.0,Female,White,Non-hispanic,163.0,False,159.0,120.0,True,NaN,True,9309,9309,Approx. 300 mg of cortical bone powder by engr...,2012-04-10,Actual,Lung Cancer,Natural,Nursing home,Blanco Villa Nursing and Rehabilitation LP
111,2012.014,True,GEFARL,85.0,Male,Hispanic,NaN,168.0,False,166.0,135.0,False,NaN,True,6852,6852,Left 4th rib midshaft,2012-04-30,Actual,Failure to thrive,Natural,Nursing home,Gracy Woods II Living Center
112,2012.015,True,GEFARL,62.0,Male,White,Non-hispanic,178.0,False,181.0,150.0,False,NaN,True,6853,6853,Left 6th rib midshaft,2012-05-07,Actual,Small cell lung cancer,Natural,Hospice facility,Christopher House
125,2012.023,True,GEFARL,56.0,Male,White,Non-hispanic,180.0,False,181.0,220.0,False,NaN,True,94,94,"Teeth #12 and #29, occipital, mandible, left a...",2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN
126,2012.023,True,GEFARL,56.0,Male,White,Non-hispanic,180.0,False,181.0,220.0,False,NaN,True,222,222,Tooth # 26,2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN
127,2012.023,True,GEFARL,56.0,Male,White,Non-hispanic,180.0,False,181.0,220.0,False,NaN,True,6861,6861,Left 6th rib midshaft,2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN
128,2012.023,True,GEFARL,56.0,Male,White,Non-hispanic,180.0,False,181.0,220.0,False,NaN,True,9257,9257,2.5 cm cortical bone fragment taken from the d...,2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN
129,2012.023,True,GEFARL,56.0,Male,White,Non-hispanic,180.0,False,181.0,220.0,False,NaN,True,19921,19921,Tooth 11,2012-06-16,Actual,Anaplastic carcinoma of peritoneum,Natural,Private residence,NaN
198,2013.014,True,GEFARL,58.0,Male,White,Non-hispanic,173.0,False,164.0,124.0,False,NaN,True,50,50,Tooth #27 (root only),2013-02-19,Actual,Ischemic stroke,Natural,Hospice facility,Christopher House
199,2013.014,True,GEFARL,58.0,Male,White,Non-hispanic,173.0,False,164.0,124.0,False,NaN,True,2237,2237,Left rib 6,2013-02-19,Actual,Ischemic stroke,Natural,Hospice facility,Christopher House
200,2013.014,True,GEFARL,58.0,Male,White,Non-hispanic,173.0,False,164.0,124.0,False,NaN,True,6890,6890,Left 6th rib midshaft,2013-02-19,Actual,Ischemic stroke,Natural,Hospice facility,Christopher House
217,2013.023,True,GEFARL,63.0,Male,White,Non-hispanic,178.0,False,175.0,150.0,True,NaN,True,6898,6898,Left 6th rib midshaft,2013-05-05,Actual,Renal Cell Carcinoma with Metastases to liver ...,Natural,Nursing home,Indian Oaks
218,2013.023,True,GEFARL,63.0,Male,White,Non-hispanic,178.0,False,175.0,150.0,True,NaN,True,19934,19934,Tooth 11,2013-05-05,Actual,Renal Cell Carcinoma with Metastases to liver ...,Natural,Nursing home,Indian Oaks
279,2014.001,True,GEFARL,72.0,Female,Hispanic,NaN,152.0,False,144.0,124.0,True,NaN,True,7146,7146,Left 6th rib midshaft,2013-12-27,Actual,Sepsis,Natural,Hospital inpatient,Guadalupe Regional Medical Center
280,2014.002,True,GEFARL,64.0,Female,White,Non-hispanic,163.0,False,165.0,240.0,True,NaN,True,7147,7147,Left 6th rib midshaft,2014-01-10,NaN,Pulmonary thromboemboli,Natural,Private residence,NaN
290,2014.006,True,GEFARL,73.0,Male,White,Non-hispanic,175.0,False,170.0,200.0,False,NaN,True,7151,7151,Right 6th rib midshaft,2014-02-10,Actual,Lung Cancer,Natural,Nursing home,Legend Oaks healthcare and Rehabilitation- Kyle
300,2014.012,True,GEFARL,64.0,Female,White,Non-hispanic,168.0,False,168.0,221.0,False,NaN,True,7159,7159,Left 6th rib midshaft,2014-03-04,Actual,Acute Cerebrovascular Accident,Natural,Hospital inpatient,South Austin Hospital
303,2014.014,True,GEFARL,78.0,Male,White,Non-hispanic,185.0,True,172.0,185.0,True,NaN,True,7160,7160,Left 6th rib midshaft,2014-02-26,NaN,Arteriosclerotic Cardiovascular Disease,Natural,Private residence,NaN
305,2014.016,True,GEFARL,59.0,Female,White,Non-hispanic,168.0,True,164.0,160.0,True,NaN,True,103,103,"Teeth #12 and #31, occipital, mandible, left a...",2014-03-13,Actual,Late effects of lung cancer probably bronchoge...,Natural,Nursing home,Colonial Manor Care Center
306,2014.016,True,GEFARL,59.0,Female,White,Non-hispanic,168.0,True,164.0,160.0,True,NaN,True,7162,7162,Left 5th rib midshaft,2014-03-13,Actual,Late effects of lung cancer probably bronchoge...,Natural,Nursing home,Colonial Manor Care Center
307,2014.016,True,GEFARL,59.0,Female,White,Non-hispanic,168.0,True,164.0,160.0,True,NaN,True,9265,9265,2.5 cm cortical bone fragment taken from the d...,2014-03-13,Actual,Late effects of lung cancer probably bronchoge...,Natural,Nursing home,Colonial Manor Care Center
308,2014.016,True,GEFARL,59.0,Female,White,Non-hispanic,168.0,True,164.0,160.0,True,NaN,True,19915,19915,Tooth 22,2014-03-13,Actual,Late effects of lung cancer probably bronchoge...,Natural,Nursing home,Colonial Manor Care Center
350,2014.044,True,GEFARL,73.0,Male,White,Non-hispanic,168.0,False,167.0,130.0,False,NaN,True,7185,7185,Left 6th rib midshaft,2014-08-31,NaN,Lung Adenocarcinoma metastatic to Brain and Bone,Natural,Hospice facility,Christopher House
377,2014.068,True,GEFARL,84.0,Male,White,Non-hispanic,183.0,False,170.0,180.0,False,NaN,True,7207,7207,Left 6th rib midshaft,2014-12-04,Actual,Hypoxemic Respiratory Failure,Natural,Hospital inpatient,St. David's Medical Center
378,2014.068,True,GEFARL,84.0,Male,White,Non-hispanic,183.0,False,170.0,180.0,False,NaN,True,19969,19969,Tooth 22,2014-12-04,Actual,Hypoxemic Respiratory Failure,Natural,Hospital inpatient,St. David's Medical Center
379,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,225.0,True,NaN,True,105,105,"Teeth #12 and #29, occipital, mandible, left a...",2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center
380,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,225.0,True,NaN,True,252,252,"Tooth #13, left rib 7",2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center
381,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,225.0,True,NaN,True,7208,7208,Left 5th rib midshaft,2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center
382,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,225.0,True,NaN,True,9234,9234,"4g section of anterior, inferior diaphysis rem...",2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center
383,2015.001,True,GEFARL,59.0,Male,White,Non-hispanic,183.0,False,179.0,225.0,True,NaN,True,9266,9266,2.5 cm cortical bone fragment taken from the d...,2015-01-05,Actual,Atherosclerotic cardiovascular disease,Natural,Hospital ER,Houston Northwest Medical Center
384,2015.002,True,GEFARL,82.0,Male,White,Non-hispanic,179.0,False,172.0,194.0,False,NaN,True,7209,7209,Left 6th rib midshaft,2015-01-12,Actual,Closed head Injury (Due to fall),Accident,Hospital inpatient,University Hospital
385,2015.003,True,GEFARL,85.0,Male,White,Non-hispanic,170.0,False,167.0,176.0,False,NaN,True,7210,7210,Left 6th rib midshaft,2015-01-29,Actual,Asphyxia (1 day),Natural,Nursing home,Chisolm Trail Nursing and Rehabilitation Center
386,2015.003,True,GEFARL,85.0,Male,White,Non-hispanic,170.0,False,167.0,176.0,False,NaN,True,12511,12511,Enamel taken from the buccal side of tooth #1,2015-01-29,Actual,Asphyxia (1 day),Natural,Nursing home,Chisolm Trail Nursing and Rehabilitation Center
387,2015.003,True,GEFARL,85.0,Male,White,Non-hispanic,170.0,False,167.0,176.0,False,NaN,True,12669,12669,"#1, buccal side",2015-01-29,Actual,Asphyxia (1 day),Natural,Nursing home,Chisolm Trail Nursing and Rehabilitation Center
396,2015.008,True,GEFARL,51.0,Male,White,Non-hispanic,175.0,True,176.0,270.0,True,NaN,True,7215,7215,Left 6th rib midshaft,2015-02-14,Actual,Small cell carcinoma of the lung with nodal me...,Natural,Hospice facility,Christopher House

In [18]:
def clean_age(col):
    # 1) Strip spaces, normalize actual NaNs and string 'nan'
    col = col.astype(str).str.strip().replace({"": np.nan, "nan": np.nan, "NaN": np.nan})
    # 2) Coerce to numeric, impossible values become NaN
    col = pd.to_numeric(col, errors="coerce")
    # 3a) If you want true missing values:
    return col.astype("Int64")

    # 3b) OR, if you want to fill with 189:
    # return col.fillna(189).astype(int)

lif_int_res_pla["AgeAtDeath"] = clean_age(lif_int_res_pla["AgeAtDeath"])
bio_des_facts["AgeAtDeath"]   = clean_age(bio_des_facts["AgeAtDeath"])

["TXSTDonorNumber", "AgeAtDeath",  "CadaverStature(cm)", "CadaverWeight(lbs)", "DateOfDeath", "DODSpecify",
         "ImmediateCOD", "MannerOfDeath", "LocationOfDeath", "FacilityOfDeath"]

In [19]:
# 1) Merge lif + bio on donor
lif_bio = lif_int_res_pla.merge(
    bio_des_facts,
    on=["TXSTDonorNumber", "AgeAtDeath",  "CadaverStature(cm)", "CadaverWeight(lbs)", "DateOfDeath", "DODSpecify",
         "ImmediateCOD", "MannerOfDeath", "LocationOfDeath", "FacilityOfDeath"],
    how="outer",          # change to 'inner' if you only want common donors
    #suffixes=("_lif", "_bio")
)
lif_bio["TXSTDonorNumber"] = lif_bio["TXSTDonorNumber"].astype("string")
lif_bio

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath,IntakeID,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),FootLength(cm),CadaverWeight(lbs),PersonalEffects,PersonalEffectsDescription,SamplesCollected,PhotographID,PhotographOverallBody,PhotographAnteriorFace,PhotographProfileLeftFace,PhotographProfileRightFace,PhotographTeeth,PhotographLeftArm,PhotographRightArm,PhotographLeftLeg,PhotographRightLeg,PhotographScars,PhotographTattoos,PhotographInjuries,PhotographJewelry,Autopsy,FullAutopsy,AbdominalAutopsy,CranialAutopsy,ThoracicAutopsy,SpinalAutopsy,OrganDonor,DonatedEyes,DonatedSkin,DonatedBones,DonatedInternalOrgans,Paperless,Donation,TXSTDSC #,DOD,Received by FACTS,Initial Placement,Length,Place of death,State,Donation.1,Curated_x,Unnamed: 10,Unnamed: 11,Curated_y,Current Facility,Sex,Race,HispanicOrigin,Height(cm),HeightEstimated,Weight(lb),WeightEstimated,Destructive Sampling,SamplingType,ElementsSampled,SpecifySamples
0,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
1,2011.008,53,2011-06-08,NaN,Lung cancer,Natural,Hospital inpatient,Christus Santa Rosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D08-2011,2011.008,2011-06-08 00:00:00,2011-06-09 00:00:00,Surface,1,"New Braunfels, TX",TX,NOK,Y,3/30/2012 buried,10/21/12 excavated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011.008,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,38.0,2011-06-09,2011-06-09,Surface,1218.0,173.0,23,NaN,%,NaN,%,False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D08-2011,2011.008,2011-06-08 00:00:00,2011-06-09 00:00:00,Surface,1,"New Braunfels, TX",TX,NOK,Y,3/30/2012 buried,10/21/12 excavated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011.011,75,2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN,91.0,2011-07-19,2011-07-19,NaN,NaN,173.0,NaN,NaN,Z,NaN,Z,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,NaN,False,False,False,False,False,D11-2011,2011.011,2011-07-18 00:00:00,2011-07-19 00:00:00,Surface,1,"Llano, TX",TX,Living,Y,1/2/2012 buried,3/25/2012 excavated,True,GEFARL,Male,White,NaN,NaN,False,218.0,False,True,91.0,91.0,"Occipital, mandible, left and right: 6th rib, ..."
4,2011.011,75,2011-07-18,NaN,Metastatic Lung Cancer,Natural,Private residence,NaN,91.0,2011-07-19,2011-07-19,NaN,NaN,173.0,NaN,NaN,Z,NaN,Z,False,False,False,False,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,NaN,False,False,False,False,False,D11-2011,2011.011,2011-07-18 00:00:00,2011-07-19 00:00:00,Surface,1,"Llano, TX",TX,Living,Y,1/2/2012 buried,3/25/2012 excavated,True,GEFARL,Male,White,NaN,NaN,False,218.0,False,True,6834.0,6834.0,Left 5th rib midshaft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2015.009,74,2015-02-25,Actual,cardiac arrest,Natural,Hospital inpatient,Heart Hospital of Austin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D09-2015,2015.009,2015-02-26 00:00:00,2015-02-26 00:00:00,surface~6pm,0,"Austin, TX",TX,Living,Y,10/4/2018 brought remains to ORPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,2015.009,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,345.0,2015-02-26,2015-02-26,Surface,1800.0,158.0,21,NaN,Ő,"""remain on body""",Ő,True,True,True,True,True,True,True,True,True,True,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D09-2015,2015.009,2015-02-26 00:00:00,2015-02-26 00:00:00,surface~6pm,0,"Austin, TX",TX,Living,Y,10/4/2018 brought remains to ORPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2023.001,74,2023-01-04,Actual,"Amyotrophic lateral sclerosis, bulbar onset",Natural,Nursing home/Long Term Care Facility,Bandera Health and Rehabilitation Center,804.0,2023-01-05,2023-01-05,Cooler,1635.0,150.0,23,87.0,̛,NaN,̛,True,True,True,True,True,True,True,True,True,True,True,True,True,True,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.001,2023-01-04 00:00:00,2023-01-05 00:00:00,cooler @1635,1,"Bandera, TX",TX,Living,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2023.002,73,2023-01-03,Actual,Colon cancer metastatic to liver,Natural,Private residence,8904 Linton Dr.,805.0,2023-01-06,2023-01-06,Cooler,1600.0,172.0,25,177.0,̜,"Diaper, orange bedsheet, orange pillow",̜,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.002,2023-01-03 00:00:00,2023-01-06 00:00:00,cooler @1600,3,"Austin, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
donors = lif_bio['TXSTDonorNumber'].astype(str).unique()
len(donors)

34

In [21]:
lif_bio.columns

Index(['TXSTDonorNumber', 'AgeAtDeath', 'DateOfDeath', 'DODSpecify',
       'ImmediateCOD', 'MannerOfDeath', 'LocationOfDeath', 'FacilityOfDeath',
       'IntakeID', 'DateReceived', 'DateOfIntake', 'InitialPlacementLocation',
       'ApproxTime', 'CadaverStature(cm)', 'FootLength(cm)',
       'CadaverWeight(lbs)', 'PersonalEffects', 'PersonalEffectsDescription',
       'SamplesCollected', 'PhotographID', 'PhotographOverallBody',
       'PhotographAnteriorFace', 'PhotographProfileLeftFace',
       'PhotographProfileRightFace', 'PhotographTeeth', 'PhotographLeftArm',
       'PhotographRightArm', 'PhotographLeftLeg', 'PhotographRightLeg',
       'PhotographScars', 'PhotographTattoos', 'PhotographInjuries',
       'PhotographJewelry', 'Autopsy', 'FullAutopsy', 'AbdominalAutopsy',
       'CranialAutopsy', 'ThoracicAutopsy', 'SpinalAutopsy', 'OrganDonor',
       'DonatedEyes', 'DonatedSkin', 'DonatedBones', 'DonatedInternalOrgans',
       'Paperless', 'Donation', 'TXSTDSC #', 'DOD', 'Received by FACTS',
       'Initial Placement', 'Length', 'Place of death', 'State', 'Donation.1',
       'Curated_x', 'Unnamed: 10', 'Unnamed: 11', 'Curated_y',
       'Current Facility', 'Sex', 'Race', 'HispanicOrigin', 'Height(cm)',
       'HeightEstimated', 'Weight(lb)', 'WeightEstimated',
       'Destructive Sampling', 'SamplingType', 'ElementsSampled',
       'SpecifySamples'],
      dtype='object')

In [22]:
# 2) Add paths (filenames, images) on donor
lif_bio_paths = paths.merge(
    lif_bio,
    on="TXSTDonorNumber",
    how="inner"            # one donor can have many path rows
)
lif_bio_paths

,filename,sample,picture_number,image_year,date,PMI Class,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath,IntakeID,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),FootLength(cm),CadaverWeight(lbs),PersonalEffects,PersonalEffectsDescription,SamplesCollected,PhotographID,PhotographOverallBody,PhotographAnteriorFace,PhotographProfileLeftFace,PhotographProfileRightFace,PhotographTeeth,PhotographLeftArm,PhotographRightArm,PhotographLeftLeg,PhotographRightLeg,PhotographScars,PhotographTattoos,PhotographInjuries,PhotographJewelry,Autopsy,FullAutopsy,AbdominalAutopsy,CranialAutopsy,ThoracicAutopsy,SpinalAutopsy,OrganDonor,DonatedEyes,DonatedSkin,DonatedBones,DonatedInternalOrgans,Paperless,Donation,TXSTDSC #,DOD,Received by FACTS,Initial Placement,Length,Place of death,State,Donation.1,Curated_x,Unnamed: 10,Unnamed: 11,Curated_y,Current Facility,Sex,Race,HispanicOrigin,Height(cm),HeightEstimated,Weight(lb),WeightEstimated,Destructive Sampling,SamplingType,ElementsSampled,SpecifySamples
0,2011.005.03.15.2011 (7).jpg,005,7,2011,3/15/2011,3,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
1,2011.005.04.20.2011 (1).JPG,005,1,2011,4/20/2011,5,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
2,2011.005.04.04.2011 (7).jpg,005,7,2011,4/4/2011,5,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
3,2011.005.03.30.2011 (1).JPG,005,1,2011,3/30/2011,5,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
4,2011.005.03.21.2011 (2).JPG,005,2,2011,3/21/2011,4,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,2023.003.01.17.2023 (11).JPG,003,11,2023,1/17/2023,2,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,2023.003.01.30.2023 (11).JPG,003,11,2023,1/30/2023,4,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1248,2023.003.01.30.2024 (11).JPG,003,11,2023,1/30/2023,5,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1249,2023.003.08.23.2023 (11).JPG,003,11,2023,8/23/2023,5,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1250,2023.003.12.13.2023 (11).JPG,003,11,2023,12/13/2023,5,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# 2) Add paths (filenames, images) on donor
lif_bio_paths = lif_bio.merge(
    paths,
    on="TXSTDonorNumber",
    how="outer"            # one donor can have many path rows
)
lif_bio_paths

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,LocationOfDeath,FacilityOfDeath,IntakeID,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),FootLength(cm),CadaverWeight(lbs),PersonalEffects,PersonalEffectsDescription,SamplesCollected,PhotographID,PhotographOverallBody,PhotographAnteriorFace,PhotographProfileLeftFace,PhotographProfileRightFace,PhotographTeeth,PhotographLeftArm,PhotographRightArm,PhotographLeftLeg,PhotographRightLeg,PhotographScars,PhotographTattoos,PhotographInjuries,PhotographJewelry,Autopsy,FullAutopsy,AbdominalAutopsy,CranialAutopsy,ThoracicAutopsy,SpinalAutopsy,OrganDonor,DonatedEyes,DonatedSkin,DonatedBones,DonatedInternalOrgans,Paperless,Donation,TXSTDSC #,DOD,Received by FACTS,Initial Placement,Length,Place of death,State,Donation.1,Curated_x,Unnamed: 10,Unnamed: 11,Curated_y,Current Facility,Sex,Race,HispanicOrigin,Height(cm),HeightEstimated,Weight(lb),WeightEstimated,Destructive Sampling,SamplingType,ElementsSampled,SpecifySamples,filename,sample,picture_number,image_year,date,PMI Class
0,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft,2011.005.03.15.2011 (7).jpg,005,7,2011,3/15/2011,3
1,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft,2011.005.04.20.2011 (1).JPG,005,1,2011,4/20/2011,5
2,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft,2011.005.04.04.2011 (7).jpg,005,7,2011,4/4/2011,5
3,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft,2011.005.03.30.2011 (1).JPG,005,1,2011,3/30/2011,5
4,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,NaN,NaN,34.0,2011-03-07,2011-03-07,Burial,1332.0,178.0,23,NaN,"""",NaN,"""",False,False,False,False,False,False,False,False,False,False,False,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,D05-2011,2011.005,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,"New Braunfels, TX",TX,Living,Y,5/4/2011 buried,12/14/11 excavated,True,GEFARL,Male,White,Non-hispanic,178.0,True,160.0,True,True,6831.0,6831.0,Left 6th rib midshaft,2011.005.03.21.2011 (2).JPG,005,2,2011,3/21/2011,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1260,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003.01.17.2023 (11).JPG,003,11,2023,1/17/2023,2
1261,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003.01.30.2023 (11).JPG,003,11,2023,1/30/2023,4
1262,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003.01.30.2024 (11).JPG,003,11,2023,1/30/2023,5
1263,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003.08.23.2023 (11).JPG,003,11,2023,8/23/2023,5
1264,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,Hospital inpatient,Methodist Hospital,806.0,2023-01-09,2023-01-09,Cooler,1645.0,166.0,24,278.0,̝,Peach colored hair scrunchie,̝,True,True,True,True,True,True,True,True,True,True,True,False,False,False,No,False,False,False,False,False,No,False,False,False,False,False,NaN,2023.003,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,"San Antonio, TX",TX,NOK,NaN,Gocha Xray NIJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003.12.13.2023 (11).JPG,003,11,2023,12/13/2023,5

In [24]:
cols = ["LocationOfDeath", "FacilityOfDeath", "IntakeID", "FootLength(cm)", "CadaverWeight(lbs)", "PersonalEffects", "PersonalEffectsDescription", "SamplesCollected",
"PhotographAnteriorFace", "PhotographProfileLeftFace", "PhotographProfileRightFace", "PhotographTeeth", "PhotographLeftArm", "PhotographRightArm",
"PhotographLeftLeg", "PhotographRightLeg", "PhotographScars", "PhotographTattoos", "PhotographInjuries", "PhotographJewelry", "AbdominalAutopsy",
"CranialAutopsy", "ThoracicAutopsy", "SpinalAutopsy", "DonatedEyes", "DonatedBones", "DonatedInternalOrgans", "Paperless", "Donation", "TXSTDSC #",
"Place of death", "State", "Donation.1", "Curated_x", "Unnamed: 10", "Unnamed: 11", "Curated_y", "Current Facility", "HeightEstimated", "WeightEstimated",
"Destructive Sampling", "SamplingType", "ElementsSampled", "SpecifySamples"]
lif_bio_paths = lif_bio_paths.drop(cols, axis=1)
lif_bio_paths

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),PhotographID,PhotographOverallBody,Autopsy,FullAutopsy,OrganDonor,DonatedSkin,DOD,Received by FACTS,Initial Placement,Length,Sex,Race,HispanicOrigin,Height(cm),Weight(lb),filename,sample,picture_number,image_year,date,PMI Class
0,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,False,False,No,False,No,False,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.15.2011 (7).jpg,005,7,2011,3/15/2011,3
1,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,False,False,No,False,No,False,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.04.20.2011 (1).JPG,005,1,2011,4/20/2011,5
2,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,False,False,No,False,No,False,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.04.04.2011 (7).jpg,005,7,2011,4/4/2011,5
3,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,False,False,No,False,No,False,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.30.2011 (1).JPG,005,1,2011,3/30/2011,5
4,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,False,False,No,False,No,False,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.21.2011 (2).JPG,005,2,2011,3/21/2011,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1260,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,True,True,No,False,No,False,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.01.17.2023 (11).JPG,003,11,2023,1/17/2023,2
1261,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,True,True,No,False,No,False,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.01.30.2023 (11).JPG,003,11,2023,1/30/2023,4
1262,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,True,True,No,False,No,False,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.01.30.2024 (11).JPG,003,11,2023,1/30/2023,5
1263,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,True,True,No,False,No,False,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.08.23.2023 (11).JPG,003,11,2023,8/23/2023,5
1264,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,True,True,No,False,No,False,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.12.13.2023 (11).JPG,003,11,2023,12/13/2023,5

In [26]:
lif_bio_paths = lif_bio_paths.sort_values(["TXSTDonorNumber", "filename"])

lif_bio_paths = (
    lif_bio_paths
    .groupby(["TXSTDonorNumber", "filename"], group_keys=False)
    .apply(lambda g: g.ffill().bfill())
    .infer_objects(copy=False)   # fix the fillna/ffill/bfill downcasting warning
)

C:\Users\mirna\AppData\Local\Temp\ipykernel_14392\1146325411.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .apply(lambda g: g.ffill().bfill())
C:\Users\mirna\AppData\Local\Temp\ipykernel_14392\1146325411.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.ffill().bfill())

In [27]:
# If Race is "White" → HispanicOrigin = "Non-hispanic"
lif_bio_paths.loc[lif_bio_paths["Race"] == "White", "HispanicOrigin"] = "Non-hispanic"

# If Race is "Hispanic" → HispanicOrigin = "Hispanic"
lif_bio_paths.loc[lif_bio_paths["Race"] == "Hispanic", "HispanicOrigin"] = "Hispanic"
lif_bio_paths

,TXSTDonorNumber,AgeAtDeath,DateOfDeath,DODSpecify,ImmediateCOD,MannerOfDeath,DateReceived,DateOfIntake,InitialPlacementLocation,ApproxTime,CadaverStature(cm),PhotographID,PhotographOverallBody,Autopsy,FullAutopsy,OrganDonor,DonatedSkin,DOD,Received by FACTS,Initial Placement,Length,Sex,Race,HispanicOrigin,Height(cm),Weight(lb),filename,sample,picture_number,image_year,date,PMI Class
6,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,0.0,0.0,No,0.0,No,0.0,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.07.2011 (15).JPG,005,15,2011,3/7/2011,1
10,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,0.0,0.0,No,0.0,No,0.0,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.11.2011 (9).JPG,005,9,2011,3/11/2011,2
0,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,0.0,0.0,No,0.0,No,0.0,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.15.2011 (7).jpg,005,7,2011,3/15/2011,3
4,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,0.0,0.0,No,0.0,No,0.0,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.21.2011 (2).JPG,005,2,2011,3/21/2011,4
12,2011.005,80,2011-03-07,NaN,Alzheimer's disease,Natural,2011-03-07,2011-03-07,Burial,1332.0,178.0,0.0,0.0,No,0.0,No,0.0,2011-03-07 00:00:00,2011-03-07 00:00:00,Surface,0,Male,White,Non-hispanic,178.0,160.0,2011.005.03.23.2011 (1).JPG,005,1,2011,3/23/2011,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1263,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,1.0,1.0,No,0.0,No,0.0,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.08.23.2023 (11).JPG,003,11,2023,8/23/2023,5
1252,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,1.0,1.0,No,0.0,No,0.0,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.09.13.2023 (11).JPG,003,11,2023,9/13/2023,5
1255,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,1.0,1.0,No,0.0,No,0.0,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.10.18.2023 (12).JPG,003,12,2023,10/18/2023,5
1245,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,1.0,1.0,No,0.0,No,0.0,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.11.15.2023 (12).JPG,003,12,2023,11/15/2023,5
1264,2023.003,35,2023-01-05,Actual,Acute myelocytic leukemia (AML),Natural,2023-01-09,2023-01-09,Cooler,1645.0,166.0,1.0,1.0,No,0.0,No,0.0,2023-01-05 00:00:00,2023-01-09 00:00:00,cooler @ 1645,4,NaN,NaN,NaN,NaN,NaN,2023.003.12.13.2023 (11).JPG,003,11,2023,12/13/2023,5

In [28]:
lif_bio_paths = lif_bio_paths[
    ~lif_bio_paths["TXSTDonorNumber"].isin([2014.02, 2015.03])
]

In [29]:
lif_bio_paths['filename'].nunique()

504

In [30]:
donors = lif_bio_paths['TXSTDonorNumber'].astype(str).unique()
len(donors)

36

In [31]:
lif_bio_paths.to_excel('donorMetadata.xlsx', index=False)